### ISSUE TITLE
iOS project with SwiftUI without storyboard

### ISSUE THREAD

**Issue by sedubois** [lazaronixon/turbo-native-initializer#3]
Thanks for this gem! Is there any way, current or that you see potentially coming, to generate an iOS project with SwiftUI without storyboard? Or perhaps it does not matter in practice?

**Comment by lazaronixon** [comment]
Unfortunately, turbo-ios hasn't implemented navigation using SwfitUI yet, but you can also call SwiftUI screens from turbo-ios. Check this screen here; it's a SwiftUI screen.

https://github.com/lazaronixon/turbo-native-initializer/blob/master/lib/turbo_native_initializer/templates/ios_stack/TurboNativeProject/Controllers/NumbersViewController.swift
